language: generic
os: linux
dist: trusty
compiler: g++
sudo: required
services: docker
env: 
  - RT_BRANCH=dev
  #- RT_BRANCH=newlocallab
  #- RT_BRANCH=waveletnew
  #- RT_BRANCH=releases

before_script:
  - git clone https://github.com/Beep6581/RawTherapee.git --branch $RT_BRANCH --single-branch
  - rm -rf RawTherapee/ci
  - cp -a ci RawTherapee
  - cd RawTherapee
  - bash ci/check_commit.sh "continuous" ${RT_BRANCH}
  #- 'if [ -e travis.cancel ]; then
  #      exit 0;
  #  fi'
  - git clone https://github.com/SpiNNakerManchester/SupportScripts.git support
  - python support/travis_blocking_stdout.py
  #- travis_wait 120 sleep infinity & sudo docker pull photoflow/docker-trusty-gtk3
  #- sudo docker run -it -v $(pwd):/sources -e "RT_BRANCH=${RT_BRANCH}" photoflow/docker-trusty-gtk3 bash /sources/ci/appimage.sh
  - travis_wait 120 sleep infinity & sudo docker pull photoflow/docker-zesty-mingw
  - sudo docker run -it -e "TRAVIS_BUILD_DIR=/sources" -e "TRAVIS_BRANCH=${RT_BRANCH}" -e "TRAVIS_COMMIT=xxx" -v $(pwd):/sources photoflow/docker-zesty-mingw bash -c /sources/ci/package-w64.sh
  #- bash ci/appimage2.sh
  - # check if zip file was successfully created
  - # abort job with failure if not
  - ls rawtherapee-w64*.zip
after_success:
  - cd $TRAVIS_BUILD_DIR/RawTherapee
  - pwd
  - ls rawtherapee-w64*.zip
  - wget -c https://github.com/aferrero2707/uploadtool/raw/master/remove.sh
  #- TRAVIS_REPO_SLUG="Beep6581/RawTherapee" bash ./remove.sh "nightly" "RawTherapee-${RT_BRANCH}-" ".AppImage"
  - wget -c https://github.com/aferrero2707/uploadtool/raw/master/upload_rotate.sh
  #- TRAVIS_REPO_SLUG="Beep6581/RawTherapee" bash  ./upload_rotate.sh "nightly" out/* >& /dev/null
  #- TRAVIS_REPO_SLUG="Beep6581/RawTherapee" bash  ./upload_rotate.sh "nightly" $TRAVIS_BUILD_DIR/RawTherapee/commit-${RT_BRANCH}.hash >& /dev/null
  - bash  ./upload_rotate.sh "continuous" rawtherapee-w64*.zip >& /dev/null
  - bash  ./upload_rotate.sh "continuous" $TRAVIS_BUILD_DIR/RawTherapee/commit-${RT_BRANCH}.hash >& 
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
    
